Repository mozilla/fxa-dev, pull requests merged in 2018-04, with the labels that each got.

#354 fix(rp): Update 123done config to new, simpler set of entries.
  roles/rp-untrusted/templates/config.json.j2
  roles/rp/templates/config.json.j2
Labels: waffle:active

#355 fix(rp): Update 123done config to new, simpler set of entries.
  roles/rp-untrusted/templates/config.json.j2
  roles/rp/templates/config.json.j2
Labels: waffle:active

#357 chore(rds): remove unreferenced rds_password from aws/environment's
  aws/environments/EXAMPLE.yml
  aws/environments/ampy.yml
  aws/environments/content.yml
  aws/environments/dcoates.yml
  aws/environments/emails3.yml
  aws/environments/featurebox.yml
  aws/environments/fxaci.yml
  aws/environments/fxadevtest.yml
  aws/environments/ios-push.yml
  aws/environments/jrgm2.yml
  aws/environments/latest.yml
  aws/environments/latest4.yml
  aws/environments/latest6.yml
  aws/environments/latestd.yml
  aws/environments/marketplace.yml
  aws/environments/nightly.yml
  aws/environments/oauth-sync.yml
  aws/environments/rfkelly.yml
  aws/environments/stable.yml
  aws/environments/stable2.yml
  aws/environments/stomlinson.yml
  aws/environments/test1.yml
  aws/environments/test2.yml
  aws/environments/test3.yml
  aws/environments/test62.yml
  aws/environments/totp.yml
  aws/environments/udara.yml
  aws/environments/ux.yml
  aws/environments/uxwip.yml
  aws/environments/vbudhram.yml
Labels: waffle:active

#358 fix(123done): make 123done restart to pick up config file changes
  roles/rp-untrusted/tasks/main.yml
  roles/rp/tasks/main.yml
Labels: waffle:active

#360 Update auth-server redirect domain
  aws/environments/fxaci.yml
  roles/auth/tasks/main.yml
Labels: waffle:active

#361 Revert "fix(123done): make 123done restart to pick up config file changes (#358)"
  roles/rp-untrusted/tasks/main.yml
  roles/rp/tasks/main.yml
Labels: waffle:active

#362 feat(environments): Add pbooth.yml
  aws/environments/pbooth.yml
Labels: waffle:active

#363 fix(rp): dont run gen_keys enymore
  roles/rp-untrusted/tasks/main.yml
  roles/rp/tasks/main.yml
Labels: waffle:active

#364 feat(keys): Allow configuration of SCOPED_KEYS_VALIDATION object.
  aws/environments/oauth-sync.yml
  roles/content/defaults/main.yml
  roles/content/tasks/main.yml
Labels: waffle:active, waffle:review

#365 feat(sms): enable permissions for SMS budget checks
  aws/cloudformation/moz-single.json
Labels: waffle:review
